// Code generated by mockery v1.0.0. DO NOT EDIT.

package programming

import mock "github.com/stretchr/testify/mock"

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

// DebugJwt provides a mock function with given fields: tokenString
func (_m *MockInterface) DebugJwt(tokenString string) (JwtDebuggerOutput, error) {
	ret := _m.Called(tokenString)

	var r0 JwtDebuggerOutput
	if rf, ok := ret.Get(0).(func(string) JwtDebuggerOutput); ok {
		r0 = rf(tokenString)
	} else {
		r0 = ret.Get(0).(JwtDebuggerOutput)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUuid provides a mock function with given fields:
func (_m *MockInterface) NewUuid() UuidOutput {
	ret := _m.Called()

	var r0 UuidOutput
	if rf, ok := ret.Get(0).(func() UuidOutput); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(UuidOutput)
	}

	return r0
}
