// Code generated by mockery v1.0.0. DO NOT EDIT.

package internet

import mock "github.com/stretchr/testify/mock"

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

// ConvertMediumToMd provides a mock function with given fields: postId
func (_m *MockInterface) ConvertMediumToMd(postId string) (ConvertMediumToMdOutput, error) {
	ret := _m.Called(postId)

	var r0 ConvertMediumToMdOutput
	if rf, ok := ret.Get(0).(func(string) ConvertMediumToMdOutput); ok {
		r0 = rf(postId)
	} else {
		r0 = ret.Get(0).(ConvertMediumToMdOutput)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(postId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
