// Code generated by mockery v1.0.0. DO NOT EDIT.

package datetime

import mock "github.com/stretchr/testify/mock"

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

// FromUnitTimestamp provides a mock function with given fields: unixTime
func (_m *MockInterface) FromUnitTimestamp(unixTime int64) FromUnixTimestampOutput {
	ret := _m.Called(unixTime)

	var r0 FromUnixTimestampOutput
	if rf, ok := ret.Get(0).(func(int64) FromUnixTimestampOutput); ok {
		r0 = rf(unixTime)
	} else {
		r0 = ret.Get(0).(FromUnixTimestampOutput)
	}

	return r0
}
